edition = "2021"

# merge_imports = true
# reorder_imports = true

# format_strings = false

# error_on_line_overflow = false

# indent_style = "Block"

max_width = 100
array_width = 80
attr_fn_like_width = 70
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 80
struct_lit_width = 24
struct_variant_width = 48
tab_spaces = 4

fn_params_layout = "Vertical"
match_arm_leading_pipes = "Never"
newline_style = "Unix"

merge_derives = true
match_block_trailing_comma = true
disable_all_formatting = false
force_explicit_abi = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
hard_tabs = false
use_field_init_shorthand = true
